# Generated by Django 4.2.13 on 2024-05-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
