# Generated by Django 4.2.13 on 2024-06-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalVisualiser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='high',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='low',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='open',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='previous_close',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='volume',
        ),
    ]
